BOOTBIN_ROLLBACK_COUNTER ?= "1"
BOOTBIN_ROLLBACK_COUNTER[doc] ?= "Rollback counter enforces that only firmware newer than the last applied version can be installed"

BOOTBIN_ROLLBACK_VERSION_DEFAULT = "${BOOTBIN_ROLLBACK_COUNTER}"
BOOTBIN_ROLLBACK_VERSION_DEFAULT:zynq = "${MACHINE}-v${BOOTBIN_ROLLBACK_COUNTER}"
BOOTBIN_ROLLBACK_VERSION_DEFAULT:zynqmp = "${MACHINE}-v${BOOTBIN_ROLLBACK_COUNTER}"

BOOTBIN_VERSION_STRING ?= "${BOOTBIN_ROLLBACK_VERSION_DEFAULT}"
