PACKAGE_FEED_URIS = "http://petalinux-uat.xilinx.com/sswreleases/basecamp/rel-${@(d.getVar('XILINX_RELEASE_VERSION') or '').split('.')[0]}/generic/rpm/release"

# Package feed names always use '_', while ARCH names might include -
PACKAGE_FEED_ARCHS ?= "${@d.getVar('PACKAGE_ARCHS').replace('-','_')}"
