# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
    "

BBFILE_COLLECTIONS += "basecamp"
BBFILE_PRIORITY_basecamp = "5"
BBFILE_PATTERN_basecamp = "^${LAYERDIR}/"
BBFILE_PATTERN_IGNORE_EMPTY_basecamp = "1"

LAYERDEPENDS_basecamp = "\
    core \
    xilinx \
    xilinx-standalone \
    xilinx-standalone-exp \
    xilinx-microblaze \
    openamp-layer \
    "

LAYERRECOMMENDS_basecamp = "\
    xilinx-virtualization \
    virtualization-layer \
    security \
    tpm-layer \
    "

LAYERSERIES_COMPAT_basecamp = "langdale"
