# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
    "

BBFILE_COLLECTIONS += "basecamp"
BBFILE_PRIORITY_basecamp = "5"
BBFILE_PATTERN_basecamp = "^${LAYERDIR}/"
BBFILE_PATTERN_IGNORE_EMPTY_basecamp = "1"

LAYERDEPENDS_basecamp = "\
    core \
    xilinx \
    xilinx-standalone \
    xilinx-standalone-sdt \
    xilinx-microblaze \
    amd-adaptive-socs-core \
    amd-vek280-versal-sdt \
    openamp-layer \
    "

LAYERRECOMMENDS_basecamp = "\
    xilinx-virtualization \
    virtualization-layer \
    security \
    tpm-layer \
    "

LAYERSERIES_COMPAT_basecamp = "scarthgap"
