# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# TO override a oe-core bbclass
BBPATH =. "${LAYERDIR}/oe-core/meta:"

# We have recipes-* directories, add to BBFILES
BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
    "

BBFILE_COLLECTIONS += "basecamp"
BBFILE_PRIORITY_basecamp = "5"
BBFILE_PATTERN_basecamp = "^${LAYERDIR}/"
BBFILE_PATTERN_IGNORE_EMPTY_basecamp = "1"

LAYERDEPENDS_basecamp = "\
    core \
    xilinx \
    xilinx-standalone \
    xilinx-standalone-sdt \
    xilinx-microblaze \
    xilinx-demos \
    amd-adaptive-socs-core \
    amd-adaptive-socs-bsp \
    openamp-layer \
    "

LAYERRECOMMENDS_basecamp = "\
    xilinx-virtualization \
    virtualization-layer \
    security \
    tpm-layer \
    "

LAYERSERIES_COMPAT_basecamp = "scarthgap"

LAYERBASE_basecamp = "${LAYERDIR}"
BASECAMP_OECORE = "${LAYERBASE_basecamp}/oe-core"

BBFILES_DYNAMIC += " \
    ros-common-layer:${LAYERDIR}/dynamic-layers/meta-ros/meta-ros-common/recipes-*/*/*.bb \
    ros-common-layer:${LAYERDIR}/dynamic-layers/meta-ros/meta-ros-common/recipes-*/*/*.bbappend \
"

# Disable some of the ros recipes which doesn't build.
BBMASK += " \
        meta-ros/meta-ros2-jazzy/generated-recipes/fuse/ \
        meta-ros/meta-ros2-jazzy/recipes-bbappends/fuse/ \
        meta-ros/meta-ros2-jazzy/recipes-support/fuse/ \
        "
