require conf/distro/poky-altcfg.conf

include conf/distro/include/basecamp-feed.conf

# Because we are no longer strictly poky-altcfg, set distro variables

DISTRO = "basecamp"
DISTRO_NAME = "Basecamp (based on poky-altcfg the Yocto Project Reference Distro)"

DISTROOVERRIDES = "poky:poky-altcfg:basecamp"

BASECAMP_VERSION = "1.0"

# Set to "release" for major releases and "update-1" for update releases
BASECAMP_VER_UPDATE = "alpha"

# This will be set in local.conf for CI builds
BASECAMP_VER_BUILD ?= "${@'${METADATA_REVISION}' if d.getVar('METADATA_REVISION') != '<unknown>' else 'unknown'}"

# Follow the Poky format of <Version>+<type>-<date>
DISTRO_VERSION = "${BASECAMP_VERSION}+${BASECAMP_VER_UPDATE}-${BASECAMP_VER_BUILD}"

SDK_VENDOR = "-basecampsdk"

MAINTAINER = "AMD AECG <meta-xilinx@yoctoproject.org>"

TARGET_VENDOR = "-basecamp"

# Define the ROS2 Yocto release
ROS_OE_RELEASE_SERIES = "scarthgap"

# Define ROS2 distro release
ROS_DISTRO = "jazzy"

DISTRO_FEATURES:append = " \
    virtualization \
    openamp \
    multiarch \
    security \
    tpm \
    vmsep \
    xen \
    "

DISTRO_FEATURES:append = "${@bb.utils.contains('MACHINE_FEATURES', 'mali400', ' libmali', '', d)}"

# Disable Busybox - Based on Poky example here:
# poky/meta-poky/conf/templates/default/local.conf.sample.extended

PREFERRED_PROVIDER_base-utils = "packagegroup-core-base-utils"
VIRTUAL-RUNTIME_base-utils = "packagegroup-core-base-utils"
VIRTUAL-RUNTIME_base-utils-hwclock = "util-linux-hwclock"
VIRTUAL-RUNTIME_base-utils-syslog = ""

# Set start-jupyterlab as default start daemon.
PREFERRED_PROVIDER_start-jupyter = "start-jupyterlab"

# basecamp builds should use the basecamp U-Boot script
UBOOT_BOOT_SCRIPT = "u-boot-basecamp-scr"

# Configure default users/groups
# Default rules (assumed no debug-tweaks image feature):
# * disabled root login (set by system default)
# * Add a user 'basecamp' with no password
#   - SSH won't allow passwd-less login w/o debug tweaks, so requires console login
#   - Set to immediately expire
#   - Add to the sudoers file
# * Add 'basecamp' user to the audio group
# * Add 'basecamp' user to the video group
IMAGE_CLASSES += "extrausers"
EXTRA_USERS_PARAMS ?= "\
    useradd -p '' basecamp;passwd-expire basecamp; \
    groupadd -r aie; \
    usermod -a -G aie,audio,input,video basecamp; \
"
USERADDEXTENSION:append = " amd-useradd-sudoers"
EXTRA_USERS_SUDOERS ?= "basecamp ALL=(ALL) ALL;"

# Disable OpenAMP device tree overlay package
ENABLE_OPENAMP_DTSI = "2"

# Include xen dtsi to default dtb until adding IOMMU nodes in SDT is implemented.
ENABLE_XEN_DTSI = "1"
ENABLE_XEN_QEMU_DTSI = "1"
