require conf/distro/poky-altcfg.conf

include conf/distro/include/basecamp-feed.conf

# Because we are no longer strictly poky-altcfg, set distro variables

DISTRO = "basecamp"
DISTRO_NAME = "Basecamp (based on poky-altcfg the Yocto Project Reference Distro)"

BASECAMP_VERSION = "0.5"

# Set to "release" for major releases and "update-1" for update releases
BASECAMP_VER_UPDATE = "alpha"

# This will be set in local.conf for CI builds
BASECAMP_VER_BUILD ?= "${@'${METADATA_REVISION}' if d.getVar('METADATA_REVISION') != '<unknown>' else 'unknown'}"

# Follow the Poky format of <Version>+<type>-<date>
DISTRO_VERSION = "${BASECAMP_VERSION}+${BASECAMP_VER_UPDATE}-${BASECAMP_VER_BUILD}"

SDK_VENDOR = "-basecampsdk"

MAINTAINER = "AMD AECG <meta-xilinx@yoctoproject.org>"

TARGET_VENDOR = "-basecamp"

# Disable Busybox - Based on Poky example here:
# poky/meta-poky/conf/templates/default/local.conf.sample.extended

PREFERRED_PROVIDER_base-utils = "packagegroup-core-base-utils"
VIRTUAL-RUNTIME_base-utils = "packagegroup-core-base-utils"
VIRTUAL-RUNTIME_base-utils-hwclock = "util-linux-hwclock"
VIRTUAL-RUNTIME_base-utils-syslog = ""
