require conf/distro/poky-altcfg.conf

# Because we are no longer strictly poky-altcfg, set distro variables

DISTRO = "basecamp"
DISTRO_NAME = "Basecamp (based on poky-altcfg the Yocto Project Reference Distro)"

SDK_VENDOR = "-basecampsdk"

MAINTAINER = "AMD AECG <meta-xilinx@yoctoproject.org>"

TARGET_VENDOR = "-basecamp"

# Disable Busybox - Based on Poky example here:
# poky/meta-poky/conf/templates/default/local.conf.sample.extended

PREFERRED_PROVIDER_base-utils = "packagegroup-core-base-utils"
VIRTUAL-RUNTIME_base-utils = "packagegroup-core-base-utils"
VIRTUAL-RUNTIME_base-utils-hwclock = "util-linux-hwclock"
VIRTUAL-RUNTIME_base-utils-syslog = ""
