#!/bin/sh

# EDF Build Environment Setup Script
#
# Copyright (C) 2025, Advanced Micro Devices, Inc.  All rights reserved.
#
# SPDX-License-Identifier: MIT
#

#
# Normally this is called as '. ./edf-init-build-env <builddir>'
#
# This works in most shells (not dash)
#

if [ -n "$BASH_SOURCE" ]; then
	ROOT=$(readlink -f $(dirname "$BASH_SOURCE"))
elif [ -n "$ZSH_NAME" ]; then
	ROOT=$(readlink -f $(dirname "$0"))
else
	ROOT=$(readlink -f ${PWD})
fi

# Set default template if one is not already in the env or passed
if [ -z ${TEMPLATECONF} ]; then
    TEMPLATECONF=$ROOT/sources/meta-amd-edf/conf/templates/default
fi

# Public release gen-machine-conf path
if [ -d $ROOT/sources/meta-xilinx/meta-xilinx-core/gen-machine-conf ]; then
    PATH=$ROOT/sources/meta-xilinx/meta-xilinx-core/gen-machine-conf:$PATH
fi

source $ROOT/sources/poky/oe-init-build-env "$@"
